# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxsJdIQlnOKCn2mSX8rh9ehT_UPFHVOw
"""

member_ages = [18, 20, 22, 25, 35, 42, 65]
# 資料篩選(begin)
list(filter(lambda x: x <= 25 and x >= 18, member_ages))

