# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxsJdIQlnOKCn2mSX8rh9ehT_UPFHVOw
"""

monthly_income = input("請輸入月薪：")
saving_account = input("請輸入存款：")
monthly_income = int(monthly_income)
saving_account = int(saving_account)
print(type(monthly_income))
print(type(saving_account))
if monthly_income > 40000:
    ans = "發信用卡"
if saving_account > 500000:
    ans = "發信用卡"
print(ans)

