# -*- coding: utf-8 -*-
"""WEEK7-A106260082 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DWoYAyG_eCJpClggHzruwx4m8g8JW7Qw
"""

last_id_digit = input('請輸入身分證字號的尾數:')
last_id_digit = int(last_id_digit)
remainder = last_id_digit % 2
# 條件判斷(begin)
if remainder == 0:
    ans = "偶數"
else:
    ans = "奇數"
# 條件判斷(end)
print("身分證字號尾數除以2的餘數為:{}，因此為{}".format(remainder, ans))

