# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxsJdIQlnOKCn2mSX8rh9ehT_UPFHVOw
"""

# while 迴圈(begin)
i = 65
while i <= 90:
    print("Character: {}, Order: {}, Binary: {}".format(chr(i), i, bin(i)))
    i += 1
# while 迴圈(end)

