# -*- coding: utf-8 -*-
"""WEEK2-A106260082.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dUlHDDa_b8wAJepTM6iJOj_83w8qUSRV
"""

print("Hello World!")

import this

