# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxsJdIQlnOKCn2mSX8rh9ehT_UPFHVOw
"""

#紓困
living_cost_dict = {
    '臺北市': 17005,
    '新北市': 15500,
    '桃園市': 15281,
    '臺中市': 14596,
    '臺南市': 12388,
    '高雄市': 13099,
    '金門縣': 11648,
    '連江縣': 11648,
    '非六都縣市': 12388
}
living_area = input('請輸入您的居住縣市:')
try:
    living_cost = living_cost_dict[living_area]
    print("{}的每人每月最低生活費為{:,}".format(living_area, living_cost))
except KeyError:
    print("請重新輸入!!")

