# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxsJdIQlnOKCn2mSX8rh9ehT_UPFHVOw
"""

#紓困
living_area=input("請輸入您的居住城市:")
print(living_area)


if living_area =="臺北市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 17005))
elif living_area == "新北市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 15500))
elif living_area == "桃園市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 15281))
elif living_area == "臺中市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 14596))  
elif living_area == "臺南市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 12388))
elif living_area =="高雄市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 13099))
elif living_area == "金門縣":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 11648))
elif living_area =="連江縣":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 11648))
elif living_area=="非六都縣市":
  print("{}的每人每月最低生活費為{:,}".format(living_area, 12388))
else:
  print("請重新輸入!")

