# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12l-QTSF_ftwCzMBXgcdgZBEoe-5bd7Cn
"""

#Fizz-Buzz
number=int(input('請輸入一個正整數:'))
if number%15==0 :
  print('Fizz Buzz!')
elif number%3==0 :
  print('Fizz!')
elif number%5==0:
  print('Buzz!')
else :
  print (number)

