# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12l-QTSF_ftwCzMBXgcdgZBEoe-5bd7Cn
"""

#月薪超過 4 萬或存款超過 50 萬就發信用卡
wage=int(input('請輸入你的月薪:'))
save=int(input('請輸入你的存款:')) 
if wage >40000 :
  print ("可以發信用卡!")
elif save >500000 :
  print ("可以發信用卡!")
else :
  print("不可以發信用卡喔~")

