# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12l-QTSF_ftwCzMBXgcdgZBEoe-5bd7Cn
"""

#判斷奇數偶數
user=int(input('請輸入一個正整數:'))
if user%2 ==0:
  print(user,'是個偶數')
else :
  print(user,'是個奇數')

