# -*- coding: utf-8 -*-
"""week13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ry3RZ3L5pG6E7bSr8P7Hqcms1CcYKR-Q
"""

n_vowels = 0 
for i in 'azcbobobegghakl':
    if i in ['a', 'e', 'i', 'o', 'u']:       
       n_vowels += 1
print(n_vowels)

