# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxsJdIQlnOKCn2mSX8rh9ehT_UPFHVOw
"""

test_str = 'azcbobobegghak'
n_char = len(test_str)
n_bobs = 0
for i in range(n_char - 2):
    if test_str[i:i+3] == 'bob':
        n_bobs += 1
print(n_bobs)

