# -*- coding: utf-8 -*-
"""week9 A106260082.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pa3LEURB_9Jf6lcg2yAThVuW1tuQVdNj
"""

x = int(input("請輸入起始的整數:"))
y = int(input("請輸入終止的整數:"))
i = x
while i <= y:
  if i%2 ==1:
    print(i)
  i+=1

