# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYNMbBfyXXR9A0B5yf9E8My-PVZxDOb-
"""

i = 1
while i<=100:
  if i % 15 == 0:
      print("Fizz Buzz")
  elif i % 5 == 0:
      print("Buzz")
  elif i % 3 == 0:
      print("Fizz")
  else:
      print(i)
  i+=1

