# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FMXTowEUJBLfy8pAmK1PrO1nLeV-7umf
"""

#covid19
import pandas as pd

time_series_df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
cumulative_confirmed = list(time_series_df[time_series_df['Country/Region'] == 'Taiwan*'].values.ravel()[4:].astype(int))
cumulative_confirmed_lag = list(time_series_df[time_series_df['Country/Region'] == 'Taiwan*'].values.ravel()[4:].astype(int))
print(cumulative_confirmed)
print(cumulative_confirmed_lag)

print(len(cumulative_confirmed))
print(cumulative_confirmed[-1])

cumulative_confirmed_lag.insert(0, 0)
print(len(cumulative_confirmed_lag))
print(cumulative_confirmed_lag[0])

cumulative_confirmed_lag.pop()
print(len(cumulative_confirmed_lag))
print(cumulative_confirmed_lag[-1])



print(cumulative_confirmed)
print(cumulative_confirmed_lag)
#daily_incraese=?
daily_increase=[]
i = 0
while i <107:
   dayn_increase=cumulative_confirmed[i] - cumulative_confirmed_lag[i]
   print("Day{}:每日新增確診人數{}".format(i,dayn_increase)) 
   i+=1

