# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQalMWlmIYg5v78NcPihIO3FKLXJBbXo
"""

weight=147
hight=216

bmi_hight=(hight/100)**2
bmi=weight/bmi_hight
print(bmi)

