# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQalMWlmIYg5v78NcPihIO3FKLXJBbXo
"""

ross_said=('''Let's put aside the fact that you "accidentally" pick up my grandmother's ring''')
print(ross_said)

