# -*- coding: utf-8 -*-
"""week4-A106260082.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11GHwK11wrggZ-mCegDedioT-_s_H_gF1
"""

tempc=int(input("請輸入要轉換的攝氏氣溫:"))
tempf=tempc*9/5+32

print ("經轉換後華氏氣溫為:",tempf)

again_tempf=int(input("請輸入要轉換的攝氏氣溫:"))
again_tempc=(again_tempf-32)*5/9

print("經轉換後攝氏氣溫為:",again_tempc)

weight=147
hight=216

bmi_hight=(hight/100)**2
bmi=weight/bmi_hight
print(bmi)

city=input("請輸入城市:")
weather=input("請輸入天氣:")
print('我在',city,'，天氣',weather)

ross_said=('''Let's put aside the fact that you "accidentally" pick up my grandmother's ring''')
print(ross_said)

name=input("請輸入球員姓名:")
name_hight=int(input("請輸入球員身高:"))
name_weight=int(input("請輸入球員體重:"))
name_bmi=name_weight/(name_hight/100)**2
name_bmi2=round(name_bmi,2)
print(name,"的身體質量指數為:",name_bmi2)
if name_bmi >30 :
  print(name,"是否過重:",'True')
else :
  print(name,"是否過重:",'false')

