# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQalMWlmIYg5v78NcPihIO3FKLXJBbXo
"""

city=input("請輸入城市:")
weather=input("請輸入天氣:")
print('我在',city,'，天氣',weather)

