# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQalMWlmIYg5v78NcPihIO3FKLXJBbXo
"""

tempc=int(input("請輸入要轉換的攝氏氣溫:"))
tempf=tempc*9/5+32

print ("經轉換後華氏氣溫為:",tempf)

