# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQalMWlmIYg5v78NcPihIO3FKLXJBbXo
"""

name=input("請輸入球員姓名:")
name_hight=int(input("請輸入球員身高:"))
name_weight=int(input("請輸入球員體重:"))
name_bmi=name_weight/(name_hight/100)**2
name_bmi2=round(name_bmi,2)
print(name,"的身體質量指數為:",name_bmi2)
if name_bmi >30 :
  print(name,"是否過重:",'True')
else :
  print(name,"是否過重:",'false')

