# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cQalMWlmIYg5v78NcPihIO3FKLXJBbXo
"""

again_tempf=int(input("請輸入要轉換的華氏氣溫:"))
again_tempc=(again_tempf-32)*5/9

print("經轉換後攝氏氣溫為:",again_tempc)

