# -*- coding: utf-8 -*-
"""WEEK3-A10626082 COLAB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0Xrk0aAoSipEEFqxN4MLNvaXnvsxdaE
"""

movie ="Avengers Endgame"
time =181
score =8.4

print(movie)
print(time)
print(score)

print(type(movie))
print(type(time))
print(type(score))