# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYNMbBfyXXR9A0B5yf9E8My-PVZxDOb-
"""

i = 1
while i <= 10:
    print(i)
    i += 1
print("While loop is done.")

