# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYNMbBfyXXR9A0B5yf9E8My-PVZxDOb-
"""

i = 2
while i <= 20:
    print(i)
    i += 2

