# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYNMbBfyXXR9A0B5yf9E8My-PVZxDOb-
"""

i = 1
counter = 0
while i <= 10:
    if i % 2 == 0:
        counter += 1
    i += 1
print(counter)

